# Generated by Django 4.1.7 on 2023-03-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.BinaryField(default=None, unique=True)),
                ('user_password', models.BinaryField(default=None)),
                ('user_create_date', models.DateTimeField(default=None)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_ID', models.BinaryField(default=None)),
                ('wallet_asset', models.BigIntegerField(default=None)),
                ('wallet_create_date', models.DateTimeField()),
                ('user_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webexchange.user')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(default=None, max_length=200)),
                ('asset_amount', models.IntegerField(default=0)),
                ('wallet_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webexchange.wallets')),
            ],
        ),
    ]
