# Generated by Django 4.1.7 on 2023-05-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webexchange", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="asset", name="wallet",),
        migrations.RemoveField(model_name="wallets", name="user",),
    ]
