# Generated by Django 4.1.7 on 2023-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0002_user_trade_history_wallet_delete_wallets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_trade_history',
            old_name='wallet_ID',
            new_name='in_wallet_ID',
        ),
        migrations.AddField(
            model_name='user_trade_history',
            name='out_wallet_ID',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
