# Generated by Django 4.1.7 on 2023-04-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0002_alter_wallets_wallet_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='chain',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webexchange.user'),
        ),
    ]
