# Generated by Django 4.1.7 on 2023-05-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0003_rename_wallet_id_user_trade_history_in_wallet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_trade_history',
            name='in_chain',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_trade_history',
            name='out_chain',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
