# Generated by Django 4.1.7 on 2023-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0004_user_trade_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_trade_history',
            name='asset_type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
