# Generated by Django 4.1.7 on 2023-05-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0004_user_trade_history_in_chain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_trade_history',
            old_name='in_chain',
            new_name='chain',
        ),
        migrations.RemoveField(
            model_name='user_trade_history',
            name='out_chain',
        ),
    ]
