# Generated by Django 4.1.7 on 2023-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0005_remove_wallets_wallet_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_amount',
            field=models.FloatField(default=0),
        ),
    ]
