# Generated by Django 4.1.7 on 2023-05-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0005_user_trade_history_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(default=None, max_length=255)),
                ('exchange_wallet_ID', models.CharField(default=None, max_length=255)),
                ('wallet_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Wallets',
        ),
        migrations.AddField(
            model_name='asset',
            name='wallet_ID',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='chain',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webexchange.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
