# Generated by Django 4.1.7 on 2023-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0005_rename_in_chain_user_trade_history_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=255)),
                ('wallet_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Wallets',
        ),
        migrations.RenameField(
            model_name='user_asset',
            old_name='asset_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='user_asset',
            old_name='asset_type',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='user_asset',
            old_name='user_ID',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user_trade_history',
            old_name='asset_type',
            new_name='symbol',
        ),
    ]
