# Generated by Django 4.1.7 on 2023-03-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='wallet_ID',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='wallet_asset',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
