# Generated by Django 4.1.7 on 2023-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexchange', '0002_alter_user_user_id_alter_user_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_create_date',
            field=models.DateTimeField(),
        ),
    ]
