from django.urls import path
from webexchange.views import (
    login_manage,
    error,
    home,
    register_manage,
    asset,
    usercenter,
    transaction,
    coins,
    proof,
    wallet,
    walletlogin,
    trade,
    trade_websocket,
    coins_websocket,
    trade_orders, 
    verify_callback,
    wallet_add,
)

urlpatterns = [
    path("404/", error.pagenotfound.as_view(), name="404"),
    path("", home.index.as_view(), name="index"),
    path("login/", login_manage.login.as_view(), name="login"),
    path("register/", register_manage.register.as_view(), name="register"),
    path("usercenter/<str:username>/", usercenter.usercenter.as_view(), name="usercenter"),
    path("asset/<str:username>/", asset.asset.as_view(), name="asset"),
    path("transaction/<str:username>/", transaction.transaction.as_view(), name="transaction"),
    path("coins/", coins.coins.as_view(), name="coins"),
    path("proof/", proof.proof.as_view(), name="proof"),
    path("walletlogin/", walletlogin.walletlogin.as_view(), name="walletlogin"),
    path("trade/<str:username>/", trade.trade.as_view(), name="trade"),
    path("wallet/<str:username>/", wallet.wallet.as_view(), name="wallet"),
    path("trade_websocket/", trade_websocket.trade_websocket.as_view(), name="trade_websocket"),
    path("coins_websocket/", coins_websocket.coins_websocket.as_view(), name="coins_websocket"),
    path("trade_orders/<str:username>/", trade_orders.trade_orders.as_view(), name="trade_orders"),
    path("verify_callback/<str:username>/", verify_callback.callback.as_view(), name="verify_callback"),
    path("walletadd/<str:username>/", wallet_add.walletadd.as_view(), name="walletadd"),
]
